"""create parcel tables

Revision ID: 89f1a86f8208
Revises: 
Create Date: 2026-07-27 19:04:39.559780

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '89f1a86f8208'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('parcel_types',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=30), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('parcels',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=30), nullable=False),
    sa.Column('weight', sa.Numeric(precision=10, scale=3), nullable=False),
    sa.Column('content_value_usd', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('delivery_cost_rub', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('parcel_type_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['parcel_type_id'], ['parcel_types.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_parcels_parcel_type_id'), 'parcels', ['parcel_type_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_parcels_parcel_type_id'), table_name='parcels')
    op.drop_table('parcels')
    op.drop_table('parcel_types')
    # ### end Alembic commands ###
