"""add session id to parcels

Revision ID: bcb9a9daece2
Revises: 89f1a86f8208
Create Date: 2026-08-02 14:41:38.265763

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bcb9a9daece2'
down_revision: Union[str, Sequence[str], None] = '89f1a86f8208'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('parcels', sa.Column('session_id', sa.String(length=36), nullable=False))
    op.create_index(op.f('ix_parcels_session_id'), 'parcels', ['session_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_parcels_session_id'), table_name='parcels')
    op.drop_column('parcels', 'session_id')
    # ### end Alembic commands ###
